core/urls.py
"""
This module defines the URL patterns for the Django project.

It maps the root URL and additional paths to their respective URLconfs.

URL Patterns:
-------------
- ``'admin/'``: Maps to the Django admin site.
- ``''``: Includes URL patterns from the `home` app.
- ``'user_auth/'``: Includes URL patterns from the `user_auth` app.

This file serves as the central routing configuration for the project.
"""

# Libraries and modules
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user_auth/', include('user_auth.urls')),
]

home/urls.py
"""
This module defines URL patterns for the `home` app in the Django project.

It maps URL paths to view functions and handles media files during
development.

URL Patterns:
-------------
- ``'/'``: Maps to `homepage` view function.
- ``'members/'``: Maps to `members_list` view function.
- ``'songs/'``: Maps to `songs_list` view function.
- ``'songs/<int:pk>/'``: Maps to `song_detail` view function, where
  `<int:pk>` is the primary key of the song.
- ``'events/'``: Maps to `events_list` view function.
"""

# Libraries and modules
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


app_name = 'home'


urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('members/', views.members_list, name='members'),
    path('songs/', views.songs_list, name='songs'),
    path('songs/<int:pk>/', views.song_detail, name='song_detail'),
    path('events/', views.events_list, name='events'),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 1 - 2

# Research & Resources
# 1. https://docs.djangoproject.com/en/2.1/howto/static-files/#serving-files-uploaded-by-a-user-during-development
# 2. https://stackoverflow.com/questions/5517950/django-media-url-and-media-root

user_auth/urls.py
"""
URL configuration for the `user_auth` app.

This module defines the URL patterns for handling user authentication-related
views in the `user_auth` app.

URL Patterns:
-------------
- ``''``: Maps to the `user_login` view, which handles user login.
- ``'authenticate_user'``: Maps to the `authenticate_user` view.
- ``'logout/'``: Maps to the `user_logout` view, which handles user logout.
- ``'register/'``: Maps to the `register` view, for user registration.
"""

# Libraries and modules
from django.urls import path
from . import views


app_name = 'user_auth'


urlpatterns = [
    path('', views.user_login, name='login'),
    path('authenticate_user', views.authenticate_user,
         name='authenticate_user'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
]

home/models.py
# Libraries and modules
from django.db import models


# Create your models here.
class Member(models.Model):

    """
    Represents a Member of the band.

    This model stores information about Members and Position.

    Attributes:
    -----------
        name : models.CharField
            The name of the member.
        position : models.CharField
            The member's role or position in the band.
        image : models.ImageField
            A photo or image of the member.


    Methods:
    --------
        __str__():
            Returns a string representation of the member's name.
    """

    name = models.CharField(max_length=200)
    position = models.CharField(max_length=200)
    bio = models.TextField()
    image = models.ImageField(upload_to='members/')

    def __str__(self):

        """
        Returns:
        --------
        str
            A string representation of member's name.
        """

        return self.name


class Song(models.Model):

    """
    Represents a song from this band.

    This model stores information about Songs title, writers, release date and\
    lyrics

    Attributes:
    -----------
        title : models.CharField
            The title of the songs.
        songwriters : models.CharField
            The person(s) who wrote the song.
        release_date : models.DateTimeField
            The date the song was released.
        lyrics : models.TextField
            The lyrics of the song.

    Methods:
    --------
        __str__():
            Returns a string representation of the song's title.
    """

    title = models.CharField(max_length=200)
    songwriters = models.CharField(max_length=200)
    release_date = models.DateTimeField()
    lyrics = models.TextField(blank=True, null=True)

    def __str__(self):

        """
        Returns:
        --------
        str
            A string representation of song title.
        """

        return self.title


class Event(models.Model):

    """
    Represents an upcoming event from the band.

    This model stores information about event venue, city, country and date.

    Attributes:
    -----------
        venue : models.CharField
            The venue where the event will take place.
        city : models.CharField
            The city where the event will take place.
        country : models.CharField
            The country where the event will take place.
        date : models.DateTimeField
            The date of the event.

    Methods:
    --------
        __str__():
            Returns a string representation of the event's venue.
    """

    venue = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    date = models.DateTimeField()

    def __str__(self):

        """
        Returns:
        --------
        str
            A string representation of event venue.
        """

        return self.venue

home/views.py
# Libraries and models
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Song, Member, Event


@login_required
def homepage(request):

    """
    Render home page of band.

    Displays the homepage with the navbar visible.

    Parameters:
    -----------
    request : HttpRequest
        The HTTP request object.

    Returns:
    --------
    HttpResponse
        The rendered homepage with the navbar included.
    """

    return render(request, 'home/home.html', {'show_navbar': True})


@login_required
def members_list(request):

    """
    Display a list of all current members of the band.

    Retrieves all members from the database and renders members list page.

    Parameters:
    -----------
    request : HttpRequest
        The HTTP request object.

    Returns:
    --------
    HttpResponse
        The rendered members list page with all members.
    """

    members = Member.objects.all()
    return render(request, 'home/members.html', {'members': members,
                                                 'show_navbar': True})


@login_required
def songs_list(request):

    """
    Display the list of all songs by the band.

    Retrieves all songs from database and renders the songs list page.

    Parameters:
    -----------
    request : HttpRequest
        The HTTP request object.

    Returns:
    --------
    HttpResponse
        The rendered songs list page with the list of all songs.
    """

    songs = Song.objects.all()
    return render(request, 'home/songs.html', {'songs': songs,
                                               'show_navbar': True})


@login_required
def song_detail(request, pk):

    """
    Display details of a single song.

    Retrieves the song with the given primary key (pk) from the database and
    renders the song detail page.

    Parameters:
    -----------
    request : HttpRequest
        The HTTP request object.
    pk : int
        The primary key of the song to be retrieved.

    Returns:
    --------
    HttpResponse
        The rendered song detail page with the details of the song.
    """

    song = get_object_or_404(Song, pk=pk)
    return render(request, 'home/detail.html', {'song': song,
                                                'show_navbar': True})


@login_required
def events_list(request):

    """
    Display the list of upcoming events of the band.

    Retrieves all upcoming events from the database and renders the events list
    page.

    Parameters:
    -----------
    request : HttpRequest
        The HTTP request object.

    Returns:
    --------
    HttpResponse
        The rendered events list page with the list of upcoming events.
    """

    events = Event.objects.all()
    return render(request, 'home/events.html', {'events': events,
                                                'show_navbar': True})

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% block title %}Amee & The Sobos{% endblock title %}</title>
    {% block styles %}<link rel="stylesheet" href="{% static 'home/styles.css' %}">{% endblock styles %}

</head>
<body>

    <!-- Navbar Section -->
    {% if show_navbar %}
    <nav id="home" class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

            <!-- Logo -->
            <a class="navbar-brand" href="#"><img src="{% static 'home/img/logo.png' %}" 
                alt="logo" class="img-fluid" style="max-height: 100px; border-radius: 50%"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Navlinks -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/members/' %}active{% endif %}" href="/members/">Members</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/songs/' %}active{% endif %}" href="/songs/">Songs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/events/' %}active{% endif %}" href="/events/">Upcoming Events</a>
                    </li>
                </ul>

                <!-- Check if user is authenticated -->
                {% if user.is_authenticated %}
                    <div class="d-flex align-items-center">
                        <span class="navbar-text me-2">Welcome, {{ user.first_name }} !</span>
                        <a class="btn btn-danger" href="{% url 'user_auth:logout' %}">Logout</a>
                    </div>
                {% endif %}

            </div>
        </div>
    </nav>
    {% endif %}

    <!-- Messages/ Alert Section -->
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <!-- Content Section -->
    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Footer Section -->
    <footer class="bg-light border-top text-center py-3 mt-5">
        <div class="container">
            <h6><span>2024<span> Ezra Moosa<span> | </span>Aspiring Software Engineer</h6>
        </div>
    </footer>

    <!-- Bootstrap JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

home/templates/home/detail.html
{% extends "home/base.html" %}


<!-- Title -->
{% block title %}
    {{ song.title }} | Amee & The Sobos
{% endblock title %}


<!-- Content -->
{% block content %}

    <!-- Display songwriter(s) and release date -->
    <div class="container mt-5">
        <h2>{{ song.title }}</h2>
        <p><strong>Songwriter(s):</strong> {{ song.songwriters }}</p>
        <p><strong>Release Date:</strong> {{ song.release_date }}</p>

        <!-- Display lyrics if available -->
        {% if song.lyrics %}
            <h2>Lyrics</h2>
            <p>{{ song.lyrics }}</p>
        {% else %}
            <p>No lyrics available for this song.</p>
        {% endif %}
    </div>

{% endblock content %}

home/templates/home/events.html
{% extends "home/base.html" %}


<!-- Title -->
{% block title %}
    EVENTS | Amee & The Sobos
{% endblock title %}


<!-- Content -->
{% block content %}


    <!-- Display all songs from band -->
    <div class="container mt-5">
        <h2>UpcomingEvents</h2>
        <ul class="list-group">
            {% for event in events %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div class="event">
                        <p>{{ event.venue }} <span>  {{ event.city }} | {{ event.country }}</span></p>
                    </div>
                    <span class="text-muted">{{ event.date }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
    
{% endblock content %}

home/templates/home/home.html
{% extends "home/base.html" %}


{% load static %}


<!-- Title -->
{% block title %}
    HOME | Amee & The Sobos
{% endblock title %}


<!-- Content -->
{% block content %}

    <!-- Hero Section -->
    <div class="container-fluid p-0">
        <div class="hero-section position-relative">
            <img src="{% static 'home/img/band.jpg' %}" alt="Band Image" class="img-fluid w-100"> <!-- 1 -->

            <!-- Events button -->
            <div class="inputBx">
                <p><a href="{% url 'home:events' %}">Events</a></p>
            </div>
        </div>
    </div>

    <!-- Header Section -->
    <div class="container mt-5 text-center">
        <h1>Feel the Beat, Live the Moment</h1>
    </div>

    <!-- Amsterdam Content Row -->
    <div class="container mt-5 content-row">
        <div class="row align-items-center">
            <div class="col-md-6">
                <img src="{% static 'home/img/amsterdam.jpg' %}" alt="Amsterdam" class="img-fluid"> <!-- 2 -->
            </div>
            <div class="col-md-6 d-flex align-items-center">
                <div class="w-100 text-center">
                    <h4>Amsterdam<span> | </span>October 2024</h4>
                    <p>On a magical evening in Amsterdam, music lovers gathered to experience an unforgettable concert by Amee & the Sobos. The historic venue was filled with electrifying energy as the band took to the stage, delivering a performance that left the audience mesmerized.</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Tokyo Content Row -->
    <div class="container mt-5 content-row">
        <div class="row align-items-center">
            <div class="col-md-6 d-flex align-items-center">
                <div class="w-100 text-center">
                    <h4>Tokyo<span> | </span>June 2024</h4>
                    <p>In the heart of Tokyo, an exhilarating concert by Amee & The Sobos turned an ordinary night into a spectacular celebration of music and culture. As the lights dimmed in Hibiya Open Air Concert Hall, anticipation electrified the air, setting the stage for an unforgettable performance.</p>
                </div>
            </div>
            <div class="col-md-6">
                <img src="{% static 'home/img/tokyo.jpg' %}" alt="Tokyo" class="img-fluid">
            </div>
        </div>
    </div>

    <!-- Budapest Content Row -->
    <div class="container mt-5 content-row">
        <div class="row align-items-center">
            <div class="col-md-6">
                <img src="{% static 'home/img/budapest.jpg' %}" alt="Budapest" class="img-fluid"> <!-- 3 -->
            </div>
            <div class="col-md-6 d-flex align-items-center">
                <div class="w-100 text-center">
                    <h4>Budapest<span> | </span>April 2024</h4>
                    <p>In the heart of Budapest, Amee & The Sobos delivered a spellbinding performance that transformed an ordinary evening into a musical journey. The iconic Vigadó Concert Hall was the perfect setting for this extraordinary event, with its historic charm and acoustics amplifying every note.</p>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- 
References & Resources

1. https://www.pexels.com/photo/concert-at-night-258804/
2. https://www.pexels.com/photo/people-inside-concert-hall-2263436/  
3. https://www.pexels.com/photo/fireworks-at-a-concert-19662654/ 
-->

home/templates/home/members.html
{% extends "home/base.html" %}


{% load static %}


<!-- Title -->
{% block title %}
    MEMBERS | Amee & The Sobos
{% endblock title %}


<!-- Content -->
{% block content %}

    <!-- Display all members of the band -->
    <div class="container mt-5">
        <h2>Our Members</h2>
        <div class="row">

        <!-- Iterate over every member in list -->
            {% for member in members %}
                <div class="col-md-4 mb-4">
                        <div class="card"> <!-- 8 -->
                            {% if member.image %}
                                <img src="{{ member.image.url }}" class="card-img-top" alt="{{ member.name }}">
                            {% else %}
                                <img src="{% static 'home/img/default.jpg' %}" class="card-img-top" alt="Default Image">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ member.name }}</h5>
                                <h6 class="card-subtitle mb-2">{{ member.position }}</h6>
                                <p class="card-text">{{ member.short_bio }}</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
            
        </div>
    </div>
    
{% endblock content %}

<!--
References & resources

1. https://www.pexels.com/photo/woman-singing-with-the-band-8041168/
2. https://www.vecteezy.com/png/19879198-user-icon-on-transparent-background
3. https://www.pexels.com/photo/woman-holding-a-acoustic-guitar-3401783/
4. https://www.pexels.com/photo/a-woman-holding-drumsticks-8412413/
5. https://www.pexels.com/photo/woman-playing-violin-1384867/
6. https://www.pexels.com/photo/a-man-playing-piano-inside-a-music-studio-7088371/
7. https://www.pexels.com/photo/man-playing-percussion-instrument-1703540/
8. https://getbootstrap.com/docs/4.0/components/card/
-->

home/templates/home/songs.html
{% extends "home/base.html" %}


<!-- Title -->
{% block title %}
    SONGS | Amee & The Sobos
{% endblock title %}


<!-- Content -->
{% block content %}

    <!-- Display all songs from band -->
    <div class="container mt-5">
        <h2>Songs</h2>
        <ul class="list-group">
            {% for song in songs %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div class="writers">
                        <a href="{% url 'home:song_detail' song.pk %}">{{ song.title }}</a>
                        <p> {{ song.songwriters }} </p> 
                    </div>
                    <span class="text-muted">{{ song.release_date }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock content %}